apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: hossam23/demo:v${BUILD_NUMBER}
        name: demo
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}
